server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotelsys?useSSL=false
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /pages/
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: entity